version: 2
updates:
  - package-ecosystem: "npm" # Change this to your package ecosystem (e.g., "npm", "maven", "bundler", etc.)
    versioning-strategy: "auto" # Optional: can be "increase", "lockfile-only", etc.
    directory: "/" # Location of package.json file
    schedule:
      interval: "weekly" # Can be "daily", "weekly", or "monthly"
