name: CICD

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      
      - name: Composer install
        run: sudo update-alternatives --set php /usr/bin/php8.3 && composer install
        working-directory: backend

      - name: Deploy to development server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
           cd /var/www/html/lara-angular
           git pull origin main
           composer install
