name: Frontend deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # This triggers the workflow only when changes are made in the frontend directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build Angular app
        run: ng build --configuration=production
        working-directory: frontend

      - name: Copy build folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: frontend/dist/
          target: /var/www/html/lara-angular/frontend/
