name: Frontend deployment

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # This triggers the workflow only when changes are made in the frontend directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install frontend dependencies
        run: npm install
        working-directory: frontend

      - name: Build React app
        run: npm run build
        working-directory: frontend

        
      - name: Copy build folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: frontend/build/
          target: /var/www/html/react-node-app/
          script: |
            cd /var/www/html/lara-angular-mysql-cicd/frontend/
            git pull origin main
        
